spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://[RDS-ENDPOINT]:3306/user_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.budgetmate: info
